"""Seed complet: sections + produits camerounais + ingrédients."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from app.core.database import engine, Base, SessionLocal
from app.models.models import Section, Produit, Ingredient

Base.metadata.create_all(bind=engine)
db = SessionLocal()

try:
    # ── SECTIONS ────────────────────────────────────────────────
    SECTIONS = [
        dict(code="menus_ingredients", nom="Menus & Ingrédients", description="Plats camerounais traditionnels et leurs ingrédients", icone="🥘", couleur_hex="#0D2137", ordre=1),
        dict(code="fruits",            nom="Fruits & Légumes",    description="Fruits et légumes frais du marché",                    icone="🍊", couleur_hex="#1a5c1a", ordre=2),
        dict(code="boissons",          nom="Boissons",            description="Boissons fraîches et traditionnelles",                 icone="🥤", couleur_hex="#1B4A8A", ordre=3),
        dict(code="boulangerie",       nom="Boulangerie",         description="Pain frais, pâtisseries et viennoiseries",            icone="🍞", couleur_hex="#7a3e10", ordre=4),
        dict(code="epices",            nom="Épices & Condiments", description="Épices, sauces et condiments camerounais",            icone="🌶️", couleur_hex="#8a1a1a", ordre=5),
    ]
    secs = {}
    for s in SECTIONS:
        obj = db.query(Section).filter(Section.code == s["code"]).first()
        if not obj:
            obj = Section(**s); db.add(obj); db.flush()
            print(f"  Section créée: {s['nom']}")
        secs[s["code"]] = obj

    # ── PRODUITS MENUS ──────────────────────────────────────────
    MENUS = [
        dict(nom="Eru (Okok)",       slug="eru-okok",        prix_base_fcfa=4500, prix_max_fcfa=7500,
             description="Plat traditionnel des régions du Sud-Ouest et Littoral camerounais. Feuilles d'okok broyées mitonnées avec viande de bœuf, crevettes, et waterleaf, relevées d'huile de palme rouge.",
             image_url="https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600&q=80&fit=crop",
             est_menu=True, est_populaire=True, est_nouveau=False),
        dict(nom="Ndolé",            slug="ndole",           prix_base_fcfa=3800, prix_max_fcfa=6500,
             description="Le plat national du Cameroun ! Feuilles de ndolé (plante amère) mijotées avec arachides pilées, viande ou crevettes, servies avec des plantains ou du bâton de manioc.",
             image_url="https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=600&q=80&fit=crop",
             est_menu=True, est_populaire=True, est_nouveau=False),
        dict(nom="Poulet DG",        slug="poulet-dg",       prix_base_fcfa=5500, prix_max_fcfa=8000,
             description="'Directeur Général' – poulet sauté avec plantains mûrs frits, carottes et poivrons dans une sauce tomate parfumée. Un classique festif camerounais.",
             image_url="https://images.unsplash.com/photo-1598103442097-8b74394b95c7?w=600&q=80&fit=crop",
             est_menu=True, est_populaire=True, est_nouveau=False),
        dict(nom="Koki (Gâteau de haricots)", slug="koki-gateau-haricots", prix_base_fcfa=2500, prix_max_fcfa=4000,
             description="Gâteau traditionnel de haricots à peau noire pilés, mélangés à l'huile de palme et cuits à la vapeur dans des feuilles de bananier. Riche et nourrissant.",
             image_url="https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80&fit=crop",
             est_menu=True, est_populaire=True, est_nouveau=False),
        dict(nom="Mbongo Tchobi",    slug="mbongo-tchobi",   prix_base_fcfa=5000, prix_max_fcfa=8500,
             description="Sauce noire épicée à base de mbongo (écorce noire), avec viande ou poisson fumé. Spécialité sawa (côtière) aux arômes intenses et profonds.",
             image_url="https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80&fit=crop",
             est_menu=True, est_populaire=False, est_nouveau=True),
        dict(nom="Beignets de Haricots (Accra)", slug="beignets-haricots-accra", prix_base_fcfa=500, prix_max_fcfa=1500,
             description="Beignets croustillants de haricots haricots blancs épicés, frits à l'huile. Snack populaire servi avec du piment frais.",
             image_url="https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&q=80&fit=crop",
             est_menu=True, est_populaire=True, est_nouveau=False),
        dict(nom="Achu Soup",        slug="achu-soup",       prix_base_fcfa=4200, prix_max_fcfa=7000,
             description="Soupe jaune traditionnelle des Grassfields (Nord-Ouest). Taro pilé servi avec une soupe à base de kaolin jaune, viande, et huile de palme.",
             image_url="https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80&fit=crop",
             est_menu=True, est_populaire=False, est_nouveau=True),
        dict(nom="Sauce Gombo",      slug="sauce-gombo",     prix_base_fcfa=3200, prix_max_fcfa=5500,
             description="Sauce à base de gombo (okra) haché avec viande de bœuf, poisson fumé, crevettes séchées et épices. Filante et savoureuse, servie avec du fufu ou riz.",
             image_url="https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&q=80&fit=crop",
             est_menu=True, est_populaire=False, est_nouveau=False),
        dict(nom="Nkui",             slug="nkui",            prix_base_fcfa=4000, prix_max_fcfa=7200,
             description="Soupe traditionnelle bamiléké à base de plantes médicinales et nutritives. Épaisse et filante, préparée avec des feuilles spéciales et de la viande de porc.",
             image_url="https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?w=600&q=80&fit=crop",
             est_menu=True, est_populaire=False, est_nouveau=True),
        dict(nom="Poisson Braisé",   slug="poisson-braise",  prix_base_fcfa=3000, prix_max_fcfa=5000,
             description="Poisson entier (capitaine, barracuda ou tilapia) mariné aux épices camerounaises et grillé au charbon de bois. Servi avec du bâton de manioc et piment.",
             image_url="https://images.unsplash.com/photo-1559847844-5315695dadae?w=600&q=80&fit=crop",
             est_menu=True, est_populaire=True, est_nouveau=False),
        dict(nom="Miondo (Bâton de Manioc)", slug="miondo-baton-manioc", prix_base_fcfa=300, prix_max_fcfa=1000,
             description="Bâton de manioc traditionnel du Cameroun coastal. Manioc fermenté, pilé et cuit dans des feuilles. Accompagnement incontournable des plats camerounais.",
             image_url="https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80&fit=crop",
             est_menu=False, est_populaire=True, est_nouveau=False),
        dict(nom="Fufu Corn",        slug="fufu-corn",       prix_base_fcfa=400, prix_max_fcfa=1000,
             description="Pâte de maïs fermentée de l'Ouest Cameroun. Accompagnement polyvalent pour toutes les sauces traditionnelles camerounaises.",
             image_url="https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600&q=80&fit=crop",
             est_menu=False, est_populaire=True, est_nouveau=False),
        dict(nom="Plantain Mûr Frit", slug="plantain-mur-frit", prix_base_fcfa=500, prix_max_fcfa=1500,
             description="Tranches de bananes plantains mûres frites dans l'huile de palme jusqu'à doré. Douceur naturelle caramélisée, accompagnement classique.",
             image_url="https://images.unsplash.com/photo-1587395651786-9485a4cefa3b?w=600&q=80&fit=crop",
             est_menu=False, est_populaire=True, est_nouveau=False),
    ]

    # ── PRODUITS FRUITS & LÉGUMES CAMEROUNAIS (complet) ─────────
    FRUITS = [
        # ═══ FRUITS ═══════════════════════════════════════════════
        dict(nom="Ananas du Cameroun", slug="ananas-cameroun", prix_base_fcfa=500, prix_max_fcfa=1500,
             description="Ananas sucré et juteux cultivé dans les régions du Centre et du Littoral. Riche en bromélaïne et vitamines.",
             image_url="https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Mangue Camerounaise", slug="mangue-camerounaise", prix_base_fcfa=300, prix_max_fcfa=1000,
             description="Mangue locale sucrée et parfumée. Variétés : Kent, Tommy, Amélie. Disponible de mars à juillet.",
             image_url="https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Papaye", slug="papaye", prix_base_fcfa=400, prix_max_fcfa=1200,
             description="Papaye fraîche locale, riche en papaïne et vitamine C. Idéale en salade de fruits ou jus.",
             image_url="https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Avocat", slug="avocat", prix_base_fcfa=200, prix_max_fcfa=600,
             description="Avocat vert du jardin camerounais. Chair crémeuse et riche, parfait pour accompagner les repas ou en guacamole.",
             image_url="https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Banane Plantain (vert)", slug="banane-plantain-vert", prix_base_fcfa=500, prix_max_fcfa=1500,
             description="Plantains verts frais pour cuisson. Idéal pour les chips, le pilon ou accompagner les plats en sauce.",
             image_url="https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Goyave", slug="goyave", prix_base_fcfa=250, prix_max_fcfa=800,
             description="Goyave rose sucrée et parfumée. Excellente source de vitamine C, à croquer ou en jus frais.",
             image_url="https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Banane Douce", slug="banane-douce", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Banane douce sucrée du Cameroun. Fruit de tous les jours, riche en potassium et en énergie. Se mange mûre ou en friture.",
             image_url="https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Pastèque", slug="pasteque", prix_base_fcfa=500, prix_max_fcfa=2000,
             description="Pastèque juteuse et rafraîchissante, cultivée dans le Nord et l'Adamaoua. Idéale en saison sèche.",
             image_url="https://images.unsplash.com/photo-1589984662646-e7b2e4962f18?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Orange du Cameroun", slug="orange-cameroun", prix_base_fcfa=100, prix_max_fcfa=300,
             description="Orange locale juteuse et sucrée. Cultivée dans le Centre, l'Ouest et le Littoral. Riche en vitamine C.",
             image_url="https://images.unsplash.com/photo-1547514701-42782101795e?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Citron Vert", slug="citron-vert", prix_base_fcfa=50, prix_max_fcfa=200,
             description="Citron vert local très parfumé. Indispensable pour les marinades de poisson, jus et assaisonnements camerounais.",
             image_url="https://images.unsplash.com/photo-1590502593747-42a996133562?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Pamplemousse", slug="pamplemousse", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Pamplemousse rose ou jaune cultivé au Cameroun. Jus rafraîchissant, légèrement amer et riche en vitamines.",
             image_url="https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Mandarine", slug="mandarine", prix_base_fcfa=100, prix_max_fcfa=400,
             description="Petite mandarine locale sucrée et facile à peler. Fruit populaire chez les enfants camerounais.",
             image_url="https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Corossol (Graviola)", slug="corossol-graviola", prix_base_fcfa=500, prix_max_fcfa=1500,
             description="Fruit exotique à chair blanche crémeuse et acidulée. Réputé pour ses propriétés médicinales. Excellent en jus.",
             image_url="https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=600&q=80&fit=crop",
             est_populaire=True, est_nouveau=True),
        dict(nom="Safou (Prune Africaine)", slug="safou-prune-africaine", prix_base_fcfa=300, prix_max_fcfa=800,
             description="Fruit emblématique du Cameroun à chair violette. Se mange grillé, bouilli ou nature. Saison : août à octobre.",
             image_url="https://images.unsplash.com/photo-1596363505729-4190a9506133?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Noix de Coco", slug="noix-de-coco", prix_base_fcfa=300, prix_max_fcfa=800,
             description="Noix de coco fraîche du Littoral camerounais. Eau de coco désaltérante et chair blanche nutritive.",
             image_url="https://images.unsplash.com/photo-1550828520-4cb496926fc9?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Fruit de la Passion (Maracuja)", slug="fruit-passion-maracuja", prix_base_fcfa=200, prix_max_fcfa=600,
             description="Fruit de la passion à pulpe acidulée et parfumée. Cultivé dans l'Ouest camerounais. Excellent en jus ou dessert.",
             image_url="https://images.unsplash.com/photo-1604495772376-9657f0035eb5?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),
        dict(nom="Pomme Cannelle", slug="pomme-cannelle", prix_base_fcfa=300, prix_max_fcfa=1000,
             description="Fruit tropical à écailles vertes et chair blanche sucrée. Saveur unique entre la vanille et la cannelle.",
             image_url="https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Melon", slug="melon", prix_base_fcfa=500, prix_max_fcfa=1500,
             description="Melon sucré et parfumé cultivé au Nord-Cameroun. Chair orangée juteuse, idéal en entrée ou dessert.",
             image_url="https://images.unsplash.com/photo-1571575173700-afb9492e6a50?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Pomme Cajou", slug="pomme-cajou", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Fruit du cajou avec sa noix. La pomme se mange fraîche ou en jus, la noix est torréfiée. Cultivé dans le Nord.",
             image_url="https://images.unsplash.com/photo-1590005354167-6da97870c757?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),
        dict(nom="Tamarin", slug="tamarin", prix_base_fcfa=200, prix_max_fcfa=600,
             description="Gousse de tamarin acidulée. Utilisé pour les jus rafraîchissants, bonbons et sauces. Populaire au Nord-Cameroun.",
             image_url="https://images.unsplash.com/photo-1607451938419-ecec23f50f10?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Nèfle du Japon (Bibacier)", slug="nefle-japon", prix_base_fcfa=300, prix_max_fcfa=800,
             description="Petit fruit orange à noyaux, chair sucrée et légèrement acidulée. Pousse dans les Hauts-Plateaux de l'Ouest.",
             image_url="https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Cerise du Pays", slug="cerise-pays", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Petites cerises rouges tropicales au goût sucré-acidulé. Riches en vitamine C, vendues en tas au marché.",
             image_url="https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Prune de Cythère (Prunier de Chine)", slug="prune-cythere", prix_base_fcfa=150, prix_max_fcfa=400,
             description="Fruit vert ou jaune croquant et acidulé. Se mange avec du sel et du piment. Populaire chez les enfants.",
             image_url="https://images.unsplash.com/photo-1595124323852-a078a4e9f39c?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Baobab (Pain de Singe) 200g", slug="baobab-pain-singe-200g", prix_base_fcfa=300, prix_max_fcfa=700,
             description="Pulpe séchée du fruit de baobab. Super-aliment riche en vitamine C, calcium et fibres. Se dilue en jus.",
             image_url="https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),
        dict(nom="Jujube (Datte chinoise)", slug="jujube-datte-chinoise", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Petit fruit brun-rouge sucré, consommé frais ou séché. Très populaire au Nord-Cameroun et dans l'Extrême-Nord.",
             image_url="https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600&q=80&fit=crop",
             est_populaire=False),

        # ═══ LÉGUMES ══════════════════════════════════════════════
        dict(nom="Tomates Fraîches (1kg)", slug="tomates-fraiches-kg", prix_base_fcfa=400, prix_max_fcfa=800,
             description="Tomates rouges mûres du marché local. Indispensables pour les sauces, soupes et salades africaines.",
             image_url="https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Oignons (1kg)", slug="oignons-kg", prix_base_fcfa=350, prix_max_fcfa=700,
             description="Oignons violets et blancs du Nord Cameroun. Base aromatique indispensable de la cuisine camerounaise.",
             image_url="https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Gombo Frais (500g)", slug="gombo-frais-500g", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Gombo (okra) frais du marché. Légume filant indispensable pour les sauces gombo camerounaises.",
             image_url="https://images.unsplash.com/photo-1425543103986-22abb7d7e8d2?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Macabo (Taro blanc)", slug="macabo-taro", prix_base_fcfa=300, prix_max_fcfa=800,
             description="Tubercule à chair blanche ou violette. Se consomme bouilli, pilé ou frit. Accompagnement traditionnel des sauces.",
             image_url="https://images.unsplash.com/photo-1590868309235-ea34bed7bd7f?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Igname", slug="igname", prix_base_fcfa=500, prix_max_fcfa=1500,
             description="Tubercule noble de la cuisine camerounaise. Se mange pilé, bouilli, frit ou en purée. Riche en glucides et fibres.",
             image_url="https://images.unsplash.com/photo-1591985666643-1eec5b63e02d?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Manioc Frais", slug="manioc-frais", prix_base_fcfa=200, prix_max_fcfa=600,
             description="Racine de manioc fraîche. Base alimentaire camerounaise : bouillie, frite, ou transformée en bâton, couscous, gari.",
             image_url="https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Patate Douce", slug="patate-douce", prix_base_fcfa=300, prix_max_fcfa=700,
             description="Patate douce à chair orange ou blanche. Bouillie, frite ou grillée au charbon. Riche en bêta-carotène.",
             image_url="https://images.unsplash.com/photo-1596097635121-14b63a7a7e93?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Pomme de Terre (1kg)", slug="pomme-terre-kg", prix_base_fcfa=400, prix_max_fcfa=800,
             description="Pommes de terre des Hauts-Plateaux de l'Ouest. Idéales pour frites, purée, ragoûts et accompagnements.",
             image_url="https://images.unsplash.com/photo-1518977676601-b53f82ber3f3?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Feuilles de Manioc (Kpwem) 500g", slug="feuilles-manioc-kpwem-500g", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Feuilles de manioc fraîches pilées. Ingrédient de base du Kpwem, plat traditionnel du Centre et du Sud Cameroun.",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Feuilles de Ndolé 500g", slug="feuilles-ndole-500g", prix_base_fcfa=400, prix_max_fcfa=800,
             description="Feuilles amères de ndolé fraîches ou séchées. Ingrédient principal du plat national camerounais.",
             image_url="https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Feuilles d'Okok (Eru) 500g", slug="feuilles-okok-eru-500g", prix_base_fcfa=500, prix_max_fcfa=1200,
             description="Feuilles d'okok (Gnetum africanum) finement découpées. Base du célèbre plat Eru des régions anglophones.",
             image_url="https://images.unsplash.com/photo-1515023115894-0791ecb48568?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Waterleaf (Talinum) 500g", slug="waterleaf-talinum-500g", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Feuilles succulentes riches en eau, partenaire indispensable de l'okok dans le plat Eru.",
             image_url="https://images.unsplash.com/photo-1592924802770-6c8a2039d4f5?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Morelle Noire (Zom/Huckleberry)", slug="morelle-noire-zom", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Feuilles de morelle noire (zom), légume-feuille traditionnel camerounais. Se cuisine en sauce avec huile de palme.",
             image_url="https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Épinards Locaux (500g)", slug="epinards-locaux-500g", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Épinards verts frais du marché. Riches en fer et vitamines, se cuisinent en sauce ou en accompagnement.",
             image_url="https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Foléré (Oseille de Guinée) 200g", slug="folere-oseille-guinee-200g", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Feuilles d'oseille de Guinée fraîches. Utilisées dans les sauces et les soupes, goût acidulé distinctif.",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Haricots Verts (500g)", slug="haricots-verts-500g", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Haricots verts frais cueillis du jardin. Croquants et savoureux, parfaits en accompagnement ou en salade.",
             image_url="https://images.unsplash.com/photo-1567375698348-5d9d5ae10c5b?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Aubergine Africaine (Garden Egg)", slug="aubergine-africaine-garden-egg", prix_base_fcfa=100, prix_max_fcfa=400,
             description="Petite aubergine blanche ou verte amère. Se mange crue avec une sauce, cuite en ragoût ou grillée.",
             image_url="https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Aubergine Violette", slug="aubergine-violette", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Grande aubergine violette. Grillée, farcie ou en sauce tomate. Légume polyvalent de la cuisine camerounaise.",
             image_url="https://images.unsplash.com/photo-1528826007177-f38517ce9a8b?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Concombre", slug="concombre", prix_base_fcfa=100, prix_max_fcfa=300,
             description="Concombre frais et croquant. En salade, en crudité avec du sel et piment, ou en jus rafraîchissant.",
             image_url="https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Chou Vert (Pommé)", slug="chou-vert-pomme", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Chou pommé vert des Hauts-Plateaux. En salade, sauté ou braisé. Légume économique et nutritif.",
             image_url="https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Laitue", slug="laitue", prix_base_fcfa=200, prix_max_fcfa=400,
             description="Salade verte fraîche. Base des salades composées et garniture incontournable des sandwichs camerounais.",
             image_url="https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Carottes (1kg)", slug="carottes-kg", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Carottes oranges fraîches des Hauts-Plateaux. Crues, cuites, en jus ou dans le Poulet DG.",
             image_url="https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Poivron Vert", slug="poivron-vert", prix_base_fcfa=150, prix_max_fcfa=400,
             description="Poivron vert croquant, essentiel dans les sautés, le Poulet DG et les marinades camerounaises.",
             image_url="https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Poivron Rouge", slug="poivron-rouge", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Poivron rouge sucré et coloré. Apporte couleur et saveur aux plats sautés et grillades.",
             image_url="https://images.unsplash.com/photo-1526346698789-22fd84314424?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Ail Frais (100g)", slug="ail-frais-100g", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Têtes d'ail frais. Condiment aromatique incontournable pour les marinades et les sauces camerounaises.",
             image_url="https://images.unsplash.com/photo-1540148426945-6cf22a6b2571?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Gingembre Frais (200g)", slug="gingembre-frais-200g", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Rhizome de gingembre frais. Utilisé dans les jus, tisanes, marinades et plats camerounais. Anti-inflammatoire naturel.",
             image_url="https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Courge / Citrouille", slug="courge-citrouille", prix_base_fcfa=300, prix_max_fcfa=800,
             description="Courge camerounaise. La chair se cuisine en sauce ou purée, les graines (pistache) servent pour les condiments.",
             image_url="https://images.unsplash.com/photo-1570586437263-ab629fccc818?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Maïs Frais (Épi)", slug="mais-frais-epi", prix_base_fcfa=100, prix_max_fcfa=300,
             description="Épi de maïs frais. Se mange bouilli, grillé au charbon ou transformé en couscous de maïs (fufu corn).",
             image_url="https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Arachides Fraîches (500g)", slug="arachides-fraiches-500g", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Arachides crues en coque ou décortiquées. Grillées, bouillies ou pilées pour les sauces (ndolé, légumes).",
             image_url="https://images.unsplash.com/photo-1567892737950-30c4db37cd89?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Haricots Rouges (Niébé) 1kg", slug="haricots-rouges-niebe-kg", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Haricots rouges secs camerounais. Base des koki, des beignets accra et des ragoûts protéinés.",
             image_url="https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Haricots Blancs (Cornille) 1kg", slug="haricots-blancs-cornille-kg", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Haricots à peau noire (niébé). Utilisés pour les beignets accra, les sauces et les ragoûts traditionnels.",
             image_url="https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Pistache (Graines de Courge) 200g", slug="pistache-graines-courge-200g", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Graines de courge camerounaises séchées. Pilées pour les sauces traditionnelles (sauce pistache, nnam owondo).",
             image_url="https://images.unsplash.com/photo-1541990931185-5e3f48693df4?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Persil / Céleri Frais", slug="persil-celeri-frais", prix_base_fcfa=100, prix_max_fcfa=300,
             description="Bouquet de persil et céleri frais. Herbes aromatiques essentielles pour parfumer les bouillons et les sauces.",
             image_url="https://images.unsplash.com/photo-1506807803488-8eafc15316c7?w=600&q=80&fit=crop",
             est_populaire=False),
    ]

    # ── PRODUITS BOISSONS (complètes — Cameroun) ─────────────────
    BOISSONS = [
        # ═══ EAUX MINÉRALES & PURIFIÉES ═══════════════════════════
        dict(nom="Supermont 1.5L", slug="supermont-1-5l", prix_base_fcfa=300, prix_max_fcfa=350,
             description="Eau minérale naturelle Supermont en bouteille 1.5 litre. La marque la plus connue du Cameroun.",
             image_url="https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Tangui 1.5L", slug="tangui-1-5l", prix_base_fcfa=350, prix_max_fcfa=400,
             description="Eau minérale naturelle Tangui, source de Bandjoun. Pureté et fraîcheur des Hauts-Plateaux camerounais.",
             image_url="https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Source du Pays 1.5L", slug="source-du-pays-1-5l", prix_base_fcfa=300, prix_max_fcfa=350,
             description="Eau minérale naturelle Source du Pays. Eau de source camerounaise légère et bien minéralisée.",
             image_url="https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Vitale 1.5L", slug="vitale-1-5l", prix_base_fcfa=300, prix_max_fcfa=350,
             description="Eau minérale Vitale, populaire dans les régions du Centre et du Littoral camerounais.",
             image_url="https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Eau en Sachet (Pure Water) x10", slug="eau-sachet-pure-water-x10", prix_base_fcfa=200, prix_max_fcfa=300,
             description="Sachets d'eau purifiée (50cl). La boisson la plus accessible du Cameroun, vendue partout dans la rue.",
             image_url="https://images.unsplash.com/photo-1559839914-17aae19cec71?w=600&q=80&fit=crop",
             est_populaire=True),

        # ═══ SODAS & BOISSONS GAZEUSES ════════════════════════════
        dict(nom="Coca-Cola 50cl", slug="coca-cola-50cl", prix_base_fcfa=400, prix_max_fcfa=500,
             description="Coca-Cola fraîche en canette ou bouteille 50cl. La boisson gazeuse préférée des Camerounais.",
             image_url="https://images.unsplash.com/photo-1554866585-cd94860890b7?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Fanta Orange 50cl", slug="fanta-orange-50cl", prix_base_fcfa=350, prix_max_fcfa=450,
             description="Fanta Orange pétillante en bouteille 50cl. Rafraîchissante et fruitée.",
             image_url="https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Sprite 50cl", slug="sprite-50cl", prix_base_fcfa=350, prix_max_fcfa=450,
             description="Sprite citronnée et pétillante. Boisson gazeuse rafraîchissante sans colorant.",
             image_url="https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Schweppes Tonic 33cl", slug="schweppes-tonic-33cl", prix_base_fcfa=400, prix_max_fcfa=500,
             description="Schweppes Indian Tonic, eau tonique légèrement amère. Idéale seule ou en cocktail.",
             image_url="https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Top Ananas 50cl", slug="top-ananas-50cl", prix_base_fcfa=300, prix_max_fcfa=400,
             description="Boisson gazeuse aromatisée à l'ananas, marque camerounaise des Brasseries du Cameroun (SABC).",
             image_url="https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Top Grenadine 50cl", slug="top-grenadine-50cl", prix_base_fcfa=300, prix_max_fcfa=400,
             description="Boisson gazeuse sucrée à la grenadine. Marque locale des Brasseries du Cameroun, adorée des enfants.",
             image_url="https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Malta Guinness 33cl", slug="malta-guinness-33cl", prix_base_fcfa=400, prix_max_fcfa=500,
             description="Boisson maltée non alcoolisée, riche en vitamines B. Goût sucré de malt torréfié, très populaire.",
             image_url="https://images.unsplash.com/photo-1566633806327-68e152aaf26d?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Vimto 33cl", slug="vimto-33cl", prix_base_fcfa=400, prix_max_fcfa=500,
             description="Boisson gazeuse aux fruits rouges (raisin, framboise, cassis). Très appréciée au Cameroun.",
             image_url="https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Pepsi 50cl", slug="pepsi-50cl", prix_base_fcfa=350, prix_max_fcfa=450,
             description="Pepsi Cola en bouteille 50cl. Alternative populaire au Coca-Cola sur le marché camerounais.",
             image_url="https://images.unsplash.com/photo-1554866585-cd94860890b7?w=600&q=80&fit=crop",
             est_populaire=False),

        # ═══ JUS DE FRUITS ════════════════════════════════════════
        dict(nom="Jus de Gingembre Frais", slug="jus-gingembre-frais", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Jus de gingembre frais, citronné et épicé. Préparé artisanalement. Tonifiant et digestif.",
             image_url="https://images.unsplash.com/photo-1602920068637-81de93f23c33?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Jus de Bissap (Hibiscus)", slug="jus-bissap-hibiscus", prix_base_fcfa=500, prix_max_fcfa=1200,
             description="Jus de fleurs d'hibiscus séchées, légèrement sucré et aromatisé. Riche en antioxydants et vitamine C.",
             image_url="https://images.unsplash.com/photo-1570696516188-ade861b84a49?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Jus de Foléré", slug="jus-folere", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Jus d'oseille de Guinée (foléré), boisson traditionnelle du Nord-Cameroun. Acidulée, sucrée et rafraîchissante.",
             image_url="https://images.unsplash.com/photo-1570696516188-ade861b84a49?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Jus de Baobab (Bouye)", slug="jus-baobab-bouye", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Jus crémeux de pulpe de baobab. Super-aliment riche en vitamine C et calcium, goût acidulé unique.",
             image_url="https://images.unsplash.com/photo-1602920068637-81de93f23c33?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),
        dict(nom="Jus de Tamarin", slug="jus-tamarin", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Jus de tamarin fait maison, acidulé et sucré. Boisson rafraîchissante populaire dans tout le Grand-Nord.",
             image_url="https://images.unsplash.com/photo-1602920068637-81de93f23c33?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Jus de Corossol", slug="jus-corossol", prix_base_fcfa=600, prix_max_fcfa=1200,
             description="Jus de corossol frais mixé, onctueux et légèrement acidulé. Réputé pour ses bienfaits santé.",
             image_url="https://images.unsplash.com/photo-1602920068637-81de93f23c33?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),
        dict(nom="Jus de Mangue Frais", slug="jus-mangue-frais", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Jus de mangue camerounaise pressé frais. Saveur tropicale intense, disponible de mars à juillet.",
             image_url="https://images.unsplash.com/photo-1602920068637-81de93f23c33?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Jus de Fruit de la Passion", slug="jus-fruit-passion", prix_base_fcfa=600, prix_max_fcfa=1200,
             description="Jus de maracuja frais, acidulé et parfumé. Fruit cultivé dans les Hauts-Plateaux de l'Ouest.",
             image_url="https://images.unsplash.com/photo-1602920068637-81de93f23c33?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Jus de Pastèque Frais", slug="jus-pasteque-frais", prix_base_fcfa=400, prix_max_fcfa=800,
             description="Jus de pastèque pressé, désaltérant et léger. Idéal en saison sèche au Cameroun.",
             image_url="https://images.unsplash.com/photo-1602920068637-81de93f23c33?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Jus d'Ananas Frais", slug="jus-ananas-frais", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Jus d'ananas pressé frais, sucré et acidulé. Ananas du Cameroun réputé pour sa saveur intense.",
             image_url="https://images.unsplash.com/photo-1602920068637-81de93f23c33?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Jus Cocktail Tropical", slug="jus-cocktail-tropical", prix_base_fcfa=600, prix_max_fcfa=1200,
             description="Mélange de jus de mangue, ananas, goyave et fruit de la passion. Le cocktail vitaminé camerounais.",
             image_url="https://images.unsplash.com/photo-1602920068637-81de93f23c33?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Santal Mangue 1L", slug="santal-mangue-1l", prix_base_fcfa=800, prix_max_fcfa=1000,
             description="Jus de mangue Santal en brique 1 litre. Marque importée très consommée au Cameroun.",
             image_url="https://images.unsplash.com/photo-1602920068637-81de93f23c33?w=600&q=80&fit=crop",
             est_populaire=True),

        # ═══ BOISSONS TRADITIONNELLES ═════════════════════════════
        dict(nom="Matango (Vin de Raphia)", slug="matango-vin-raphia", prix_base_fcfa=300, prix_max_fcfa=800,
             description="Vin de palme raphia fraîchement tapé. Boisson traditionnelle légèrement fermentée des régions forestières.",
             image_url="https://images.unsplash.com/photo-1566633806327-68e152aaf26d?w=600&q=80&fit=crop",
             est_populaire=True, est_nouveau=True),
        dict(nom="Mimbo (Vin de Palme)", slug="mimbo-vin-palme", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Vin de palme à huile frais, légèrement sucré et effervescent. Boisson ancestrale du Cameroun côtier.",
             image_url="https://images.unsplash.com/photo-1566633806327-68e152aaf26d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Bili-Bili (Bière de Mil)", slug="bili-bili-biere-mil", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Bière artisanale de mil fermenté, boisson traditionnelle du Grand-Nord Cameroun. Légèrement acide et trouble.",
             image_url="https://images.unsplash.com/photo-1566633806327-68e152aaf26d?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),
        dict(nom="Arki (Alcool de Mil)", slug="arki-alcool-mil", prix_base_fcfa=300, prix_max_fcfa=700,
             description="Eau-de-vie de mil distillée artisanalement dans le Nord-Cameroun. Spiritueux traditionnel très fort.",
             image_url="https://images.unsplash.com/photo-1566633806327-68e152aaf26d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Kossam (Lait Caillé Peul)", slug="kossam-lait-caille-peul", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Lait caillé fermenté des éleveurs Peuls/Bororo, consommé nature ou sucré. Probiotique naturel camerounais.",
             image_url="https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Odontol (Liqueur locale)", slug="odontol-liqueur-locale", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Liqueur artisanale camerounaise à base de plantes et d'écorces macérées. Consommé lors des cérémonies.",
             image_url="https://images.unsplash.com/photo-1566633806327-68e152aaf26d?w=600&q=80&fit=crop",
             est_populaire=False),

        # ═══ BIÈRES CAMEROUNAISES ═════════════════════════════════
        dict(nom="33 Export (Bière) 65cl", slug="33-export-biere-65cl", prix_base_fcfa=600, prix_max_fcfa=800,
             description="Bière blonde 33 Export, la plus emblématique du Cameroun. Brassée par les Brasseries du Cameroun (SABC).",
             image_url="https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Castel Beer 65cl", slug="castel-beer-65cl", prix_base_fcfa=600, prix_max_fcfa=800,
             description="Bière blonde Castel, brassée localement au Cameroun par UCB (Union Camerounaise de Brasseries).",
             image_url="https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Beaufort (Bière) 65cl", slug="beaufort-biere-65cl", prix_base_fcfa=600, prix_max_fcfa=800,
             description="Bière Beaufort, blonde légère et rafraîchissante. Une des marques phares des Brasseries du Cameroun.",
             image_url="https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Mutzig 65cl", slug="mutzig-65cl", prix_base_fcfa=700, prix_max_fcfa=900,
             description="Bière premium Mutzig, forte et corsée. Brassée au Cameroun, appréciée pour son goût prononcé.",
             image_url="https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Guinness Cameroun 65cl", slug="guinness-cameroun-65cl", prix_base_fcfa=700, prix_max_fcfa=900,
             description="Guinness Foreign Extra Stout, bière brune puissante brassée au Cameroun. Goût de malt torréfié intense.",
             image_url="https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Kadji Beer 65cl", slug="kadji-beer-65cl", prix_base_fcfa=600, prix_max_fcfa=800,
             description="Bière Kadji, marque locale camerounaise. Blonde légère et accessible, brassée par UCB.",
             image_url="https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Isenbeck 65cl", slug="isenbeck-65cl", prix_base_fcfa=600, prix_max_fcfa=800,
             description="Bière blonde Isenbeck, brassée au Cameroun. Légère et désaltérante, consommée lors des retrouvailles.",
             image_url="https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Harp Lager 65cl", slug="harp-lager-65cl", prix_base_fcfa=600, prix_max_fcfa=800,
             description="Bière Harp Lager, blonde douce et maltée. Présente dans les bars et restaurants camerounais.",
             image_url="https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Manyan 65cl", slug="manyan-65cl", prix_base_fcfa=600, prix_max_fcfa=800,
             description="Bière Manyan, marque populaire camerounaise. Blonde légère au goût houblonné agréable.",
             image_url="https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80&fit=crop",
             est_populaire=False),

        # ═══ BOISSONS ÉNERGISANTES & AUTRES ═══════════════════════
        dict(nom="Red Bull 25cl", slug="red-bull-25cl", prix_base_fcfa=800, prix_max_fcfa=1000,
             description="Boisson énergisante Red Bull importée. Caféine, taurine et vitamines B. Populaire chez les jeunes.",
             image_url="https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Monster Energy 50cl", slug="monster-energy-50cl", prix_base_fcfa=800, prix_max_fcfa=1200,
             description="Boisson énergisante Monster importée. Boost d'énergie pour les longues journées et soirées.",
             image_url="https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Power Horse 25cl", slug="power-horse-25cl", prix_base_fcfa=500, prix_max_fcfa=700,
             description="Boisson énergisante Power Horse, très répandue au Cameroun. Alternative locale moins chère au Red Bull.",
             image_url="https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Lait Peak Concentré 160g", slug="lait-peak-concentre-160g", prix_base_fcfa=400, prix_max_fcfa=500,
             description="Lait concentré sucré Peak en boîte. Incontournable pour le café, le thé et les bouillies camerounaises.",
             image_url="https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Lait Cowbell Sachet 25g x10", slug="lait-cowbell-sachet-x10", prix_base_fcfa=300, prix_max_fcfa=400,
             description="Lait en poudre Cowbell en sachets individuels. Pratique et économique, utilisé dans le café et la bouillie.",
             image_url="https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Yaourt Nature (pot 125ml)", slug="yaourt-nature-pot-125ml", prix_base_fcfa=250, prix_max_fcfa=400,
             description="Yaourt nature brassé, produit localement. Dessert frais et probiotique, nature ou avec du sucre.",
             image_url="https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Café Camerounais Moulu 250g", slug="cafe-camerounais-moulu-250g", prix_base_fcfa=1500, prix_max_fcfa=2500,
             description="Café arabica ou robusta du Cameroun, torréfié et moulu. Arôme intense des plantations de l'Ouest et du Nord-Ouest.",
             image_url="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Thé Camerounais (Ndawara) 100g", slug="the-camerounais-ndawara-100g", prix_base_fcfa=500, prix_max_fcfa=800,
             description="Thé noir cultivé dans les plantations de Ndawara (Nord-Ouest). Infusion corsée et parfumée.",
             image_url="https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Ovaltine / Chocolat Chaud 400g", slug="ovaltine-chocolat-chaud-400g", prix_base_fcfa=1500, prix_max_fcfa=2000,
             description="Poudre chocolatée Ovaltine pour petit-déjeuner chaud. Mélange cacao, malt et lait. Très consommé au Cameroun.",
             image_url="https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80&fit=crop",
             est_populaire=True),
    ]

    # ── PRODUITS BOULANGERIE & PÂTISSERIES CAMEROUNAISES ─────────
    BOULANGERIE = [
        # ═══ PAINS ════════════════════════════════════════════════
        dict(nom="Pain Boulangerie (baguette)", slug="pain-boulangerie-baguette", prix_base_fcfa=250, prix_max_fcfa=300,
             description="Baguette de pain frais croustillante, cuite au four chaque matin. Le pain camerounais par excellence.",
             image_url="https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Pain de Mie (tranché)", slug="pain-mie-tranche", prix_base_fcfa=700, prix_max_fcfa=1200,
             description="Pain de mie moelleux en tranches. Idéal pour sandwichs, toasts et petits-déjeuners rapides.",
             image_url="https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Pain Complet / Blé Entier", slug="pain-complet-ble-entier", prix_base_fcfa=500, prix_max_fcfa=800,
             description="Pain complet au blé entier, riche en fibres. Alternative santé au pain blanc classique.",
             image_url="https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Pain Sucré Camerounais", slug="pain-sucre-camerounais", prix_base_fcfa=300, prix_max_fcfa=500,
             description="Pain brioché sucré et moelleux, doré au four. Goûter préféré des enfants camerounais, parfumé à la vanille.",
             image_url="https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Pain au Lait", slug="pain-au-lait", prix_base_fcfa=200, prix_max_fcfa=400,
             description="Petit pain au lait doux et moelleux. Parfait au petit-déjeuner avec du beurre, confiture ou chocolat.",
             image_url="https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Pain Saucisson", slug="pain-saucisson", prix_base_fcfa=300, prix_max_fcfa=500,
             description="Pain fourré au saucisson de Francfort. Snack populaire vendu dans les boulangeries et kiosques camerounais.",
             image_url="https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Pain Chocolat / Croissant", slug="pain-chocolat-croissant", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Viennoiseries françaises adaptées au goût camerounais. Feuilletées et beurrées, disponibles dans les boulangeries modernes.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),

        # ═══ BEIGNETS CAMEROUNAIS ═════════════════════════════════
        dict(nom="Beignets Chauds (10 pcs)", slug="beignets-chauds-10pcs", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Beignets ronds et moelleux frits à l'huile, légèrement sucrés. Incontournables du petit-déjeuner camerounais.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Beignets de Haricots (Accra) x10", slug="beignets-haricots-accra-x10", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Beignets croustillants de haricots blancs épicés, frits à l'huile. Snack populaire servi avec du piment.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Beignets de Banane (Makala) x10", slug="beignets-banane-makala-x10", prix_base_fcfa=500, prix_max_fcfa=800,
             description="Beignets de banane plantain mûre frits, sucrés et parfumés. Goûter populaire vendu dans la rue au Cameroun.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Mandazi (Beignet sucré)", slug="mandazi-beignet-sucre", prix_base_fcfa=300, prix_max_fcfa=800,
             description="Beignets triangulaires à la noix de coco, légèrement sucrés et épicés. Populaires en Afrique centrale.",
             image_url="https://images.unsplash.com/photo-1619898804872-82038fa25da5?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Puff-Puff (Beignets Soufflés) x10", slug="puff-puff-beignets-souffles-x10", prix_base_fcfa=500, prix_max_fcfa=800,
             description="Beignets soufflés dorés et moelleux, version anglophone camerounaise. Frits et saupoudrés de sucre.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Beignets de Maïs (Corn Chaff)", slug="beignets-mais-corn-chaff", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Beignets à base de pâte de maïs frais râpé, sucrés et frits. Spécialité des régions anglophones du Cameroun.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=False),

        # ═══ GÂTEAUX & PÂTISSERIES TRADITIONNELLES ═══════════════
        dict(nom="Gâteau de Fête (Anniversaire)", slug="gateau-fete", prix_base_fcfa=5000, prix_max_fcfa=15000,
             description="Gâteau à étages décoré, parfumé à la vanille ou au chocolat. Idéal pour anniversaires et cérémonies camerounaises.",
             image_url="https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Koki (Gâteau de Haricots)", slug="koki-boulangerie", prix_base_fcfa=500, prix_max_fcfa=1500,
             description="Gâteau traditionnel de haricots à peau noire pilés, mélangés à l'huile de palme, cuit à la vapeur dans des feuilles de bananier.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Gâteau de Pistache (Nnam Ngon)", slug="gateau-pistache-nnam-ngon", prix_base_fcfa=500, prix_max_fcfa=1200,
             description="Gâteau traditionnel aux graines de courge (pistache), cuit à la vapeur dans des feuilles de bananier. Spécialité Béti.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Nnam Owondo (Gâteau d'Arachide)", slug="nnam-owondo-gateau-arachide", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Gâteau d'arachide pilée cuit à la vapeur dans des feuilles. Accompagnement traditionnel protéiné du Centre-Sud.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Gâteau de Maïs (Corn Bread)", slug="gateau-mais-corn-bread", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Pain de maïs sucré et moelleux cuit au four. Recette héritée des régions de l'Ouest et du Nord-Ouest.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Gâteau de Manioc (Bobolo Sucré)", slug="gateau-manioc-bobolo-sucre", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Gâteau moelleux à base de manioc râpé, sucré et cuit au four. Texture fondante, goût légèrement acidulé.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),
        dict(nom="Gâteau de Patate Douce", slug="gateau-patate-douce", prix_base_fcfa=400, prix_max_fcfa=800,
             description="Gâteau moelleux à base de patate douce râpée, sucre et œufs. Pâtisserie rustique et naturellement sucrée.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),
        dict(nom="Chin-Chin (Biscuits Frits) 200g", slug="chin-chin-biscuits-frits-200g", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Petits morceaux de pâte croustillants frits et sucrés. Biscuit populaire pour l'apéritif et les fêtes au Cameroun.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Kouign (Galette sucrée)", slug="kouign-galette-sucree", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Galette de farine sucrée et croustillante, vendue en tas dans les marchés camerounais. Snack bon marché.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Caramel (Toffee Camerounais) x20", slug="caramel-toffee-camerounais-x20", prix_base_fcfa=200, prix_max_fcfa=400,
             description="Bonbons caramel artisanaux camerounais, fondants en bouche. Fabriqués avec du lait concentré et du sucre.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Donuts / Beignets Américains x6", slug="donuts-beignets-americains-x6", prix_base_fcfa=1000, prix_max_fcfa=2000,
             description="Donuts moelleux glacés au sucre ou au chocolat. Pâtisserie moderne présente dans les boulangeries urbaines.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Tarte aux Fruits", slug="tarte-aux-fruits", prix_base_fcfa=2000, prix_max_fcfa=5000,
             description="Tarte pâtissière garnie de fruits tropicaux frais (mangue, ananas, papaye). Dessert de fête camerounais.",
             image_url="https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Éclairs au Chocolat x3", slug="eclairs-chocolat-x3", prix_base_fcfa=1500, prix_max_fcfa=2500,
             description="Éclairs fourrés à la crème pâtissière et nappés de chocolat. Pâtisserie française adoptée au Cameroun.",
             image_url="https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600&q=80&fit=crop",
             est_populaire=False),

        # ═══ BOUILLIES & PETITS-DÉJEUNERS ═════════════════════════
        dict(nom="Bouillie de Maïs (Pap) 500g", slug="bouillie-mais-pap-500g", prix_base_fcfa=300, prix_max_fcfa=500,
             description="Farine de maïs pour bouillie (pap). Petit-déjeuner traditionnel camerounais, cuite avec du lait et du sucre.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Bouillie de Riz 500g", slug="bouillie-riz-500g", prix_base_fcfa=300, prix_max_fcfa=500,
             description="Farine de riz pour bouillie crémeuse. Petit-déjeuner doux et nourrissant, idéal pour les enfants.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Bouillie de Soja 500g", slug="bouillie-soja-500g", prix_base_fcfa=400, prix_max_fcfa=600,
             description="Farine de soja torréfiée pour bouillie protéinée. Alternative nutritive très consommée au Cameroun.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Sanga (Bouillie de Maïs Fermenté)", slug="sanga-bouillie-mais-fermente", prix_base_fcfa=200, prix_max_fcfa=400,
             description="Bouillie de maïs fermenté au goût acidulé, servie chaude. Petit-déjeuner traditionnel du Centre et du Sud.",
             image_url="https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80&fit=crop",
             est_populaire=True),
    ]

    # ── PRODUITS ÉPICES & CONDIMENTS (complets) ──────────────────
    EPICES = [
        # ═══ PIMENTS ══════════════════════════════════════════════
        dict(nom="Piment Rouge Frais (100g)", slug="piment-rouge-frais-100g", prix_base_fcfa=200, prix_max_fcfa=500,
             description="Piments rouges piquants frais du marché camerounais. Indispensables pour pimenter sauces et marinades.",
             image_url="https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Piment Vert Frais (100g)", slug="piment-vert-frais-100g", prix_base_fcfa=200, prix_max_fcfa=400,
             description="Piments verts frais, moins piquants que les rouges. Utilisés dans les sauces et comme condiment de table.",
             image_url="https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Piment Séché Moulu (50g)", slug="piment-seche-moulu-50g", prix_base_fcfa=200, prix_max_fcfa=400,
             description="Piment rouge séché et moulu en poudre fine. Pratique pour assaisonner tous les plats camerounais.",
             image_url="https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Piment Fumé (Ndzing) 50g", slug="piment-fume-ndzing-50g", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Piment fumé traditionnel camerounais (ndzing). Arôme fumé intense, utilisé dans les sauces noires et les marinades.",
             image_url="https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Piment de Cayenne (50g)", slug="piment-cayenne-50g", prix_base_fcfa=300, prix_max_fcfa=500,
             description="Poudre de piment de Cayenne, très piquant. Utilisé dans les marinades et sauces piquantes camerounaises.",
             image_url="https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Scotch Bonnet (Piment Habanero) 100g", slug="scotch-bonnet-habanero-100g", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Piment Scotch Bonnet très piquant et parfumé. Utilisé frais ou en sauce pour relever les plats.",
             image_url="https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=600&q=80&fit=crop",
             est_populaire=False),

        # ═══ ÉPICES CAMEROUNAISES TRADITIONNELLES ═════════════════
        dict(nom="Mbongo (Écorce noire) 50g", slug="mbongo-ecorce-noire-50g", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Écorce noire séchée, épice principale du Mbongo Tchobi. Arôme fumé et amer, typiquement camerounais.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Njansang (Graine) 100g", slug="njansang-graine-100g", prix_base_fcfa=600, prix_max_fcfa=1200,
             description="Graines de njansang torréfiées, épice distinctive de la cuisine camerounaise. Utilisées moulues dans les sauces.",
             image_url="https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Nkui (Poudre d'Écorces) 50g", slug="nkui-poudre-ecorces-50g", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Mélange d'écorces et de plantes pour la sauce Nkui bamiléké. Épaississant naturel aux vertus médicinales.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),
        dict(nom="Pèbè (Aidan Fruit) 50g", slug="pebe-aidan-fruit-50g", prix_base_fcfa=400, prix_max_fcfa=800,
             description="Gousses de pèbè séchées au parfum intense et boisé. Épice camerounaise pour soupes, sauces et tisanes post-partum.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Ésesé (Poivre de Guinée) 50g", slug="esese-poivre-guinee-50g", prix_base_fcfa=500, prix_max_fcfa=900,
             description="Poivre de Guinée (graines de Selim), épice poivrée et légèrement amère. Parfume les sauces et les bouillons.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Poivre Blanc de Penja 50g", slug="poivre-blanc-penja-50g", prix_base_fcfa=800, prix_max_fcfa=1500,
             description="Poivre blanc de Penja, IGP camerounaise mondialement reconnue. Arôme subtil et puissant, le meilleur poivre au monde.",
             image_url="https://images.unsplash.com/photo-1473101119397-76f3c72bd0e4?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Poivre Noir de Penja 50g", slug="poivre-noir-penja-50g", prix_base_fcfa=700, prix_max_fcfa=1300,
             description="Poivre noir de Penja, cru intense et fruité. Terroir volcanique unique du Moungo camerounais.",
             image_url="https://images.unsplash.com/photo-1473101119397-76f3c72bd0e4?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Djindja (4 Côtés) 50g", slug="djindja-4-cotes-50g", prix_base_fcfa=400, prix_max_fcfa=800,
             description="Fruit séché à 4 côtés (Tetrapleura tetraptera). Épice parfumée pour soupes, sauces et médecine traditionnelle.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Noix de Muscade 50g", slug="noix-muscade-50g", prix_base_fcfa=500, prix_max_fcfa=900,
             description="Noix de muscade entière ou moulue. Épice chaude et parfumée utilisée dans les sauces et pâtisseries.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Clou de Girofle 50g", slug="clou-girofle-50g", prix_base_fcfa=400, prix_max_fcfa=700,
             description="Clous de girofle entiers, arôme puissant et chaud. Utilisés dans les bouillons, tisanes et marinades camerounaises.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Cannelle en Bâtons (50g)", slug="cannelle-batons-50g", prix_base_fcfa=400, prix_max_fcfa=700,
             description="Bâtons de cannelle pour infusions, pâtisseries et plats mijotés. Épice douce et chaleureuse.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Curcuma en Poudre 50g", slug="curcuma-poudre-50g", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Poudre de curcuma jaune, anti-inflammatoire naturel. Utilisé dans les sauces et plats camerounais modernes.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),
        dict(nom="Curry en Poudre 50g", slug="curry-poudre-50g", prix_base_fcfa=300, prix_max_fcfa=500,
             description="Mélange de curry en poudre. Utilisé dans les riz sautés, poulets et plats camerounais d'inspiration asiatique.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Feuille de Laurier (20g)", slug="feuille-laurier-20g", prix_base_fcfa=200, prix_max_fcfa=400,
             description="Feuilles de laurier séchées pour parfumer les bouillons, ragoûts et sauces mijotées.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Thym Séché (20g)", slug="thym-seche-20g", prix_base_fcfa=200, prix_max_fcfa=400,
             description="Thym séché aromatique. Herbe indispensable pour les marinades de viande et poisson au Cameroun.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Basilic Frais / Séché (20g)", slug="basilic-frais-seche-20g", prix_base_fcfa=200, prix_max_fcfa=400,
             description="Basilic tropical camerounais, frais ou séché. Arôme puissant pour sauces tomate et grillades.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Country Onion (Oignon de Brousse) 50g", slug="country-onion-oignon-brousse-50g", prix_base_fcfa=500, prix_max_fcfa=900,
             description="Oignon de brousse séché, épice rare et parfumée de la forêt camerounaise. Arôme unique pour les sauces noires.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),
        dict(nom="Graines de Selim (Kieng) 50g", slug="graines-selim-kieng-50g", prix_base_fcfa=400, prix_max_fcfa=700,
             description="Graines de Selim (Xylopia aethiopica), poivre éthiopien. Épice fumée et poivrée pour les sauces traditionnelles.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),

        # ═══ HUILES & MATIÈRES GRASSES ════════════════════════════
        dict(nom="Huile de Palme (1L)", slug="huile-palme-1l", prix_base_fcfa=1200, prix_max_fcfa=1800,
             description="Huile de palme rouge non raffinée, riche en bêta-carotène. Base de nombreux plats camerounais.",
             image_url="https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Huile de Palme Blanche (1L)", slug="huile-palme-blanche-1l", prix_base_fcfa=1500, prix_max_fcfa=2000,
             description="Huile de palme raffinée (blanche). Pour fritures et cuissons, sans coloration. Utilisée dans la cuisine moderne.",
             image_url="https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Huile d'Arachide (1L)", slug="huile-arachide-1l", prix_base_fcfa=1500, prix_max_fcfa=2200,
             description="Huile d'arachide pressée, idéale pour les fritures et les sauces. Goût léger de noisette.",
             image_url="https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Huile Végétale (Mayor/Diamaor) 1L", slug="huile-vegetale-mayor-1l", prix_base_fcfa=1200, prix_max_fcfa=1600,
             description="Huile végétale raffinée de marques locales (Mayor, Diamaor). Polyvalente pour fritures et cuisson quotidienne.",
             image_url="https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Beurre de Karité (200g)", slug="beurre-karite-200g", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Beurre de karité pur du Nord-Cameroun. Utilisé en cuisine traditionnelle et en cosmétique. Nourrissant et riche.",
             image_url="https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Huile de Coco Vierge (250ml)", slug="huile-coco-vierge-250ml", prix_base_fcfa=1000, prix_max_fcfa=1800,
             description="Huile de noix de coco vierge pressée à froid du Littoral. Cuisine, pâtisserie et soins naturels.",
             image_url="https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80&fit=crop",
             est_populaire=False, est_nouveau=True),

        # ═══ CONDIMENTS & ASSAISONNEMENTS ═════════════════════════
        dict(nom="Cube Bouillon Maggi (x12)", slug="cube-bouillon-maggi-x12", prix_base_fcfa=150, prix_max_fcfa=200,
             description="Cubes de bouillon Maggi, assaisonnement universel de la cuisine camerounaise. Boîte de 12 cubes.",
             image_url="https://images.unsplash.com/photo-1587132117046-008c6586a5ac?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Cube Jumbo (x12)", slug="cube-jumbo-x12", prix_base_fcfa=150, prix_max_fcfa=200,
             description="Cubes de bouillon Jumbo, alternative populaire au Maggi. Saveur riche pour assaisonner tous les plats.",
             image_url="https://images.unsplash.com/photo-1587132117046-008c6586a5ac?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Sel de Cuisine (500g)", slug="sel-cuisine-500g", prix_base_fcfa=150, prix_max_fcfa=250,
             description="Sel de table fin ou gros sel pour la cuisine quotidienne. Conditionnement 500g.",
             image_url="https://images.unsplash.com/photo-1520358026095-c9b4db6d7963?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Poivre Noir Moulu (50g)", slug="poivre-noir-moulu-50g", prix_base_fcfa=300, prix_max_fcfa=600,
             description="Poivre noir moulu, arôme intense et piquant. Assaisonnement de base pour marinades et sauces.",
             image_url="https://images.unsplash.com/photo-1473101119397-76f3c72bd0e4?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Crevettes Séchées (100g)", slug="crevettes-sechees-100g", prix_base_fcfa=800, prix_max_fcfa=1500,
             description="Crevettes séchées fumées, saveur intense. Indispensables pour parfumer sauces et bouillons africains.",
             image_url="https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Poisson Fumé (200g)", slug="poisson-fume-200g", prix_base_fcfa=800, prix_max_fcfa=1500,
             description="Poisson fumé séché (maquereau, bar). Condiment essentiel des sauces camerounaises pour ajouter de l'umami.",
             image_url="https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Écrevisses Séchées (100g)", slug="ecrevisses-sechees-100g", prix_base_fcfa=1000, prix_max_fcfa=2000,
             description="Écrevisses de rivière séchées et moulues. Condiment précieux pour les sauces riches en saveur du Cameroun.",
             image_url="https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Potasse Alimentaire (Kangwa) 50g", slug="potasse-alimentaire-kangwa-50g", prix_base_fcfa=200, prix_max_fcfa=400,
             description="Potasse (kangwa) utilisée pour adoucir les légumes verts et attendrir les haricots. Ingrédient traditionnel camerounais.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Vinaigre (50cl)", slug="vinaigre-50cl", prix_base_fcfa=300, prix_max_fcfa=500,
             description="Vinaigre blanc ou de cidre pour assaisonnement, marinades et conservation des aliments.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Moutarde de Dijon (200g)", slug="moutarde-dijon-200g", prix_base_fcfa=500, prix_max_fcfa=800,
             description="Moutarde importée pour marinades de viande, sandwichs et sauces vinaigrette.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Sauce Soja (250ml)", slug="sauce-soja-250ml", prix_base_fcfa=500, prix_max_fcfa=800,
             description="Sauce soja importée pour les sautés, marinades et cuisine camerounaise d'inspiration asiatique.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
        dict(nom="Mayonnaise (300g)", slug="mayonnaise-300g", prix_base_fcfa=500, prix_max_fcfa=800,
             description="Mayonnaise crémeuse pour sandwichs, salades et accompagnement des grillades camerounaises.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Ketchup (300g)", slug="ketchup-300g", prix_base_fcfa=500, prix_max_fcfa=800,
             description="Ketchup tomate pour frites, sandwichs et snacks. Condiment populaire dans les fast-foods camerounais.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Pâte d'Arachide (500g)", slug="pate-arachide-500g", prix_base_fcfa=500, prix_max_fcfa=1000,
             description="Pâte d'arachide pure camerounaise (beurre de cacahuète). Base des sauces arachide, ndolé et tartines.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Concentré de Tomate (400g)", slug="concentre-tomate-400g", prix_base_fcfa=400, prix_max_fcfa=600,
             description="Double concentré de tomate en boîte. Indispensable pour les sauces, ragoûts et riz jollof camerounais.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Sucre en Poudre (1kg)", slug="sucre-poudre-1kg", prix_base_fcfa=600, prix_max_fcfa=800,
             description="Sucre blanc en poudre pour la cuisine, les pâtisseries et les boissons. Conditionnement 1 kg.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=True),
        dict(nom="Bicarbonate de Soude (100g)", slug="bicarbonate-soude-100g", prix_base_fcfa=200, prix_max_fcfa=400,
             description="Bicarbonate de soude alimentaire. Utilisé pour les beignets, le nettoyage des légumes et la pâtisserie.",
             image_url="https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80&fit=crop",
             est_populaire=False),
    ]

    # ── INGRÉDIENTS DES MENUS ───────────────────────────────────
    INGREDIENTS_PAR_SLUG = {
        "eru-okok": [
            dict(nom="Feuilles d'Okok (Eru)", est_obligatoire=True,  type_saisie="curseur", unite="g",
                 quantite_defaut=500, quantite_min=200, quantite_max=1000, prix_min_fcfa=500, prix_max_fcfa=2500, prix_defaut_fcfa=1200),
            dict(nom="Viande de Bœuf",       est_obligatoire=True,  type_saisie="curseur", unite="g",
                 quantite_defaut=300, quantite_min=100, quantite_max=800, prix_min_fcfa=500, prix_max_fcfa=4000, prix_defaut_fcfa=1500),
            dict(nom="Waterleaf (Talinum)",  est_obligatoire=True,  type_saisie="curseur", unite="g",
                 quantite_defaut=200, quantite_min=100, quantite_max=500, prix_min_fcfa=200, prix_max_fcfa=1000, prix_defaut_fcfa=400),
            dict(nom="Crevettes Séchées",    est_obligatoire=False, type_saisie="curseur", unite="g",
                 quantite_defaut=50,  quantite_min=0,   quantite_max=200, prix_min_fcfa=0,   prix_max_fcfa=1500, prix_defaut_fcfa=400),
            dict(nom="Huile de Palme",       est_obligatoire=True,  type_saisie="curseur", unite="cl",
                 quantite_defaut=10,  quantite_min=5,   quantite_max=30,  prix_min_fcfa=100, prix_max_fcfa=600,  prix_defaut_fcfa=200),
            dict(nom="Poisson Fumé",         est_obligatoire=False, type_saisie="curseur", unite="g",
                 quantite_defaut=100, quantite_min=0,   quantite_max=300, prix_min_fcfa=0,   prix_max_fcfa=1500, prix_defaut_fcfa=600),
        ],
        "ndole": [
            dict(nom="Feuilles de Ndolé",    est_obligatoire=True,  type_saisie="curseur", unite="g",
                 quantite_defaut=400, quantite_min=200, quantite_max=800, prix_min_fcfa=400, prix_max_fcfa=2000, prix_defaut_fcfa=800),
            dict(nom="Arachides Pilées",     est_obligatoire=True,  type_saisie="curseur", unite="g",
                 quantite_defaut=150, quantite_min=50,  quantite_max=400, prix_min_fcfa=200, prix_max_fcfa=1200, prix_defaut_fcfa=500),
            dict(nom="Viande de Bœuf",       est_obligatoire=False, type_saisie="curseur", unite="g",
                 quantite_defaut=250, quantite_min=0,   quantite_max=600, prix_min_fcfa=0,   prix_max_fcfa=3000, prix_defaut_fcfa=1200),
            dict(nom="Crevettes Fraîches",   est_obligatoire=False, type_saisie="curseur", unite="g",
                 quantite_defaut=100, quantite_min=0,   quantite_max=300, prix_min_fcfa=0,   prix_max_fcfa=2000, prix_defaut_fcfa=800),
            dict(nom="Huile de Palme",       est_obligatoire=True,  type_saisie="curseur", unite="cl",
                 quantite_defaut=8,   quantite_min=4,   quantite_max=20,  prix_min_fcfa=100, prix_max_fcfa=400,  prix_defaut_fcfa=160),
            dict(nom="Oignons",             est_obligatoire=True,  type_saisie="curseur", unite="g",
                 quantite_defaut=100, quantite_min=50,  quantite_max=250, prix_min_fcfa=50,  prix_max_fcfa=200,  prix_defaut_fcfa=100),
        ],
        "poulet-dg": [
            dict(nom="Poulet (morceaux)",    est_obligatoire=True,  type_saisie="curseur", unite="g",
                 quantite_defaut=600, quantite_min=300, quantite_max=1200, prix_min_fcfa=1500, prix_max_fcfa=6000, prix_defaut_fcfa=2500),
            dict(nom="Plantains Mûrs",       est_obligatoire=True,  type_saisie="curseur", unite="pcs",
                 quantite_defaut=2,   quantite_min=1,   quantite_max=6,   prix_min_fcfa=200, prix_max_fcfa=1200,  prix_defaut_fcfa=500),
            dict(nom="Tomates Fraîches",     est_obligatoire=True,  type_saisie="curseur", unite="g",
                 quantite_defaut=200, quantite_min=100, quantite_max=500, prix_min_fcfa=100, prix_max_fcfa=500,   prix_defaut_fcfa=200),
            dict(nom="Poivron Vert/Rouge",   est_obligatoire=False, type_saisie="curseur", unite="pcs",
                 quantite_defaut=1,   quantite_min=0,   quantite_max=3,   prix_min_fcfa=0,   prix_max_fcfa=300,   prix_defaut_fcfa=100),
            dict(nom="Carottes",             est_obligatoire=False, type_saisie="curseur", unite="g",
                 quantite_defaut=100, quantite_min=0,   quantite_max=300, prix_min_fcfa=0,   prix_max_fcfa=300,   prix_defaut_fcfa=150),
            dict(nom="Huile de Cuisson",     est_obligatoire=True,  type_saisie="curseur", unite="cl",
                 quantite_defaut=5,   quantite_min=3,   quantite_max=15,  prix_min_fcfa=100, prix_max_fcfa=400,   prix_defaut_fcfa=200),
        ],
        "mbongo-tchobi": [
            dict(nom="Mbongo (Écorce Noire)", est_obligatoire=True, type_saisie="curseur", unite="g",
                 quantite_defaut=30, quantite_min=10, quantite_max=80, prix_min_fcfa=200, prix_max_fcfa=800, prix_defaut_fcfa=400),
            dict(nom="Viande de Porc/Bœuf",  est_obligatoire=True,  type_saisie="curseur", unite="g",
                 quantite_defaut=500, quantite_min=200, quantite_max=1000, prix_min_fcfa=1000, prix_max_fcfa=5000, prix_defaut_fcfa=2500),
            dict(nom="Poisson Fumé",          est_obligatoire=False, type_saisie="curseur", unite="g",
                 quantite_defaut=100, quantite_min=0,   quantite_max=300, prix_min_fcfa=0,    prix_max_fcfa=1500, prix_defaut_fcfa=600),
            dict(nom="Njansang",              est_obligatoire=False, type_saisie="curseur", unite="g",
                 quantite_defaut=20,  quantite_min=0,   quantite_max=60,  prix_min_fcfa=0,    prix_max_fcfa=600,  prix_defaut_fcfa=200),
            dict(nom="Huile de Palme",        est_obligatoire=True,  type_saisie="curseur", unite="cl",
                 quantite_defaut=8,   quantite_min=4,   quantite_max=25,  prix_min_fcfa=100,  prix_max_fcfa=500,  prix_defaut_fcfa=200),
        ],
    }

    def seed_section(section_code, items, extra_kwargs=None):
        sec = secs[section_code]
        for i, item in enumerate(items):
            existing = db.query(Produit).filter(Produit.slug == item["slug"]).first()
            if not existing:
                kwargs = dict(
                    section_id=sec.id,
                    est_actif=True,
                    stock_dispo=True,
                    est_menu=item.get("est_menu", False),
                    est_populaire=item.get("est_populaire", False),
                    est_nouveau=item.get("est_nouveau", False),
                    ordre=i,
                    nom=item["nom"],
                    slug=item["slug"],
                    description=item.get("description",""),
                    prix_base_fcfa=item["prix_base_fcfa"],
                    prix_max_fcfa=item.get("prix_max_fcfa", item["prix_base_fcfa"]),
                    image_url=item.get("image_url",""),
                )
                if extra_kwargs:
                    kwargs.update(extra_kwargs)
                p = Produit(**kwargs)
                db.add(p)
                db.flush()

                # Ingrédients
                ingrs = INGREDIENTS_PAR_SLUG.get(item["slug"], [])
                for j, ing in enumerate(ingrs):
                    db.add(Ingredient(produit_id=p.id, ordre=j, **ing))

                print(f"  Produit: {item['nom']}")

    seed_section("menus_ingredients", MENUS)
    seed_section("fruits",    FRUITS)
    seed_section("boissons",  BOISSONS)
    seed_section("boulangerie", BOULANGERIE)
    seed_section("epices",    EPICES)

    db.commit()
    print("\n✅ Seed produits terminé avec succès!")

except Exception as e:
    db.rollback()
    print(f"❌ ERREUR: {e}")
    import traceback; traceback.print_exc()
    raise
finally:
    db.close()
