import { create } from 'zustand'
import { persist } from 'zustand/middleware'

const fr = {
  // ─── Navigation
  nav_accueil: 'Accueil',
  nav_catalogue: 'Catalogue',
  nav_panier: 'Panier',
  nav_connexion: 'Connexion',
  nav_inscription: 'Inscription',
  nav_commandes: 'Mes commandes',
  nav_profil: 'Mon profil',
  nav_fidelite: 'Programme Fidélité',
  nav_admin: 'Administration',
  nav_livreur: 'Espace Livreur',
  nav_deconnexion: 'Déconnexion',
  nav_notifications: 'Notifications',
  nav_recherche: 'Rechercher',
  nav_promo_banner: 'Livraison à domicile — Yaoundé & Douala · Frais à partir de 500 FCFA',
  nav_create_account: 'Créer un compte gratuit',
  // Sections menu
  sec_menus: 'Menus',
  sec_fruits: 'Fruits',
  sec_boissons: 'Boissons',
  sec_boulangerie: 'Boulangerie',
  sec_epices: 'Épices',

  // ─── Accueil
  hero_tag: 'Composez votre repas',
  hero_title: 'Vos ingrédients frais,\nchoisis par vous',
  hero_sub: 'Choisissez chaque ingrédient, ajustez les quantités, et composez le plat qui vous ressemble.',
  hero_cta_compose: 'Composer mon repas',
  hero_cta_browse: 'Voir le catalogue',
  how_title: 'Comment ça marche ?',
  how_step1: 'Choisissez vos ingrédients',
  how_step1_desc: 'Parcourez le catalogue et ajoutez les ingrédients de votre choix.',
  how_step2: 'Payez en toute sécurité',
  how_step2_desc: 'Carte bancaire, Mobile Money, PayPal ou espèces à la livraison.',
  how_step3: 'Votre livreur achète au marché',
  how_step3_desc: 'Nos livreurs achètent vos ingrédients frais et vous les livrent.',
  popular_title: 'Populaires',
  new_title: 'Nouveautés',
  see_all: 'Voir tout',

  // ─── Catalogue
  catalogue_compose: 'Composez votre repas',
  catalogue_search: 'Rechercher un produit...',
  catalogue_filter: 'Filtrer',
  catalogue_sort: 'Trier',
  catalogue_no_result: 'Aucun produit trouvé',
  catalogue_add_to_cart: 'Ajouter au panier',
  catalogue_customize: 'Personnaliser',
  catalogue_view: 'Voir le détail',
  product_ingredients: 'Ingrédients',
  product_quantity: 'Quantité',
  product_unit_price: 'Prix unitaire',
  product_total: 'Total',
  product_back: 'Retour',
  product_buy: 'Acheter maintenant',

  // ─── Panier / Checkout
  cart_title: 'Mon panier',
  cart_empty: 'Votre panier est vide',
  cart_empty_cta: 'Découvrir le catalogue',
  cart_total: 'Total',
  cart_subtotal: 'Sous-total',
  cart_delivery: 'Frais de livraison',
  cart_free_delivery: 'Livraison offerte',
  cart_checkout: 'Commander',
  cart_continue_shopping: 'Continuer mes achats',
  cart_remove: 'Supprimer',
  checkout_title: 'Finaliser la commande',
  checkout_step_address: 'Adresse',
  checkout_step_slot: 'Livraison',
  checkout_step_payment: 'Paiement',
  checkout_address: 'Adresse de livraison',
  checkout_address_add: 'Ajouter une adresse',
  checkout_address_select: 'Sélectionnez une adresse',
  checkout_address_label: 'Libellé',
  checkout_address_quartier: 'Quartier',
  checkout_address_ville: 'Ville',
  checkout_address_rue: 'Rue (optionnel)',
  checkout_address_save: 'Enregistrer',
  checkout_address_cancel: 'Annuler',
  checkout_slot: 'Créneau de livraison',
  checkout_slot_morning: 'Matin',
  checkout_slot_noon: 'Midi',
  checkout_slot_evening: 'Soir',
  checkout_weight: 'Poids estimé de la commande (optionnel)',
  checkout_weight_hint: 'Une estimation du poids permet de calculer les frais de livraison précis.',
  checkout_payment: 'Mode de paiement',
  checkout_next: 'Suivant',
  checkout_confirm: 'Confirmer & Payer',
  checkout_back: 'Retour',
  payment_mtn: 'MTN Mobile Money',
  payment_orange: 'Orange Money',
  payment_stripe: 'Carte bancaire (Visa/Mastercard)',
  payment_paypal: 'PayPal',
  payment_cash: 'Espèces à la livraison',
  payment_pay_on_delivery: 'Payez à la réception',
  payment_instant: 'Paiement instantané',
  payment_phone_label: 'Numéro Mobile Money',
  payment_phone_placeholder: '6XX XXX XXX',
  payment_stripe_info: 'Vous serez redirigé vers la page sécurisée Stripe pour saisir vos informations de carte bancaire (Visa, Mastercard).',
  payment_paypal_info: 'Vous serez redirigé vers PayPal pour finaliser le paiement avec votre compte PayPal ou carte internationale.',
  payment_momo_info: 'Vous recevrez une notification USSD sur votre téléphone pour confirmer le paiement avec votre code PIN.',
  payment_secure: 'Paiement 100% sécurisé · Données chiffrées',
  // Statut paiement
  verifying_payment: 'Vérification du paiement…',
  please_wait: 'Merci de patienter, nous confirmons votre transaction.',
  payment_confirmed: 'Paiement confirmé !',
  order_success_msg: 'Votre commande a bien été enregistrée. Vous recevrez une notification dès qu\'elle sera prête.',
  payment_failed: 'Paiement non confirmé',
  payment_failed_msg: 'La transaction n\'a pas pu être validée.',
  back_to_cart: 'Retour au panier',
  // Confirmation
  order_confirmed: 'Commande confirmée !',
  invoice: 'Facture',
  view_orders: 'Voir mes commandes',
  back_home: 'Retour à l\'accueil',

  // ─── Connexion / Inscription
  login_title: 'Bon retour !',
  login_sub: 'Connectez-vous pour accéder à votre compte',
  login_phone: 'Téléphone',
  login_password: 'Mot de passe',
  login_forgot: 'Mot de passe oublié ?',
  login_submit: 'Se connecter',
  login_no_account: 'Pas encore de compte ?',
  login_create: 'Créer un compte',
  signup_title: 'Créer un compte',
  signup_sub: 'Rejoignez ComeBuy en quelques secondes',
  signup_name: 'Nom complet',
  signup_email: 'Email (optionnel)',
  signup_phone: 'Téléphone',
  signup_password: 'Mot de passe',
  signup_role: 'Je suis',
  signup_role_client: 'Client',
  signup_role_delivery: 'Livreur',
  signup_submit: 'S\'inscrire',
  signup_have_account: 'Déjà un compte ?',
  signup_login: 'Se connecter',
  otp_title: 'Vérification',
  otp_sub: 'Entrez le code OTP reçu par SMS',
  otp_resend: 'Renvoyer le code',
  otp_verify: 'Vérifier',

  // ─── Profil
  profile_title: 'Mon profil',
  profile_personal: 'Informations personnelles',
  profile_name: 'Nom complet',
  profile_email: 'Email',
  profile_phone: 'Téléphone',
  profile_role: 'Rôle',
  profile_member_since: 'Membre depuis',
  profile_save: 'Enregistrer',
  profile_change_password: 'Changer le mot de passe',
  profile_old_password: 'Ancien mot de passe',
  profile_new_password: 'Nouveau mot de passe',
  profile_confirm_password: 'Confirmer le nouveau mot de passe',
  // Commandes
  orders_title: 'Mes commandes',
  orders_empty: 'Vous n\'avez encore aucune commande',
  orders_status_pending: 'En attente de paiement',
  orders_status_paid: 'Payée',
  orders_status_preparing: 'En préparation',
  orders_status_delivering: 'En livraison',
  orders_status_delivered: 'Livrée',
  orders_status_cancelled: 'Annulée',
  orders_track: 'Suivre',
  orders_details: 'Détails',
  // Adresses
  addresses_title: 'Mes adresses',
  addresses_empty: 'Aucune adresse enregistrée',
  addresses_add: 'Ajouter une adresse',
  addresses_default: 'Adresse par défaut',
  addresses_edit: 'Modifier',
  addresses_delete: 'Supprimer',
  // Fidélité
  loyalty_title: 'Programme Fidélité',
  loyalty_points: 'Points',
  loyalty_level: 'Niveau',
  // Notifications
  notif_title: 'Notifications',
  notif_empty: 'Aucune notification',
  notif_mark_read: 'Tout marquer lu',
  // Aide
  help_title: 'Aide & Support',
  help_contact: 'Nous contacter',

  // ─── Footer
  footer_about: 'À propos',
  footer_help: 'Aide',
  footer_terms: 'Conditions générales',
  footer_privacy: 'Politique de confidentialité',
  footer_rights: 'Tous droits réservés.',
  footer_follow: 'Suivez-nous',

  // ─── Common
  loading: 'Chargement…',
  error_generic: 'Une erreur est survenue',
  retry: 'Réessayer',
  cancel: 'Annuler',
  confirm: 'Confirmer',
  save: 'Enregistrer',
  delete: 'Supprimer',
  edit: 'Modifier',
  close: 'Fermer',
  yes: 'Oui',
  no: 'Non',
  search_placeholder: 'Rechercher…',
  required: 'Requis',
  optional: 'Optionnel',
  total: 'Total',
  qty: 'Qté',
  // ─── App
  lang_label: 'FR',
  lang_switch_tooltip: 'Switch to English',
}

const en = {
  // ─── Navigation
  nav_accueil: 'Home',
  nav_catalogue: 'Catalogue',
  nav_panier: 'Cart',
  nav_connexion: 'Login',
  nav_inscription: 'Sign up',
  nav_commandes: 'My orders',
  nav_profil: 'My profile',
  nav_fidelite: 'Loyalty program',
  nav_admin: 'Administration',
  nav_livreur: 'Rider area',
  nav_deconnexion: 'Logout',
  nav_notifications: 'Notifications',
  nav_recherche: 'Search',
  nav_promo_banner: 'Home delivery — Yaoundé & Douala · From 500 FCFA',
  nav_create_account: 'Create a free account',
  sec_menus: 'Meals',
  sec_fruits: 'Fruits',
  sec_boissons: 'Drinks',
  sec_boulangerie: 'Bakery',
  sec_epices: 'Spices',

  // ─── Home
  hero_tag: 'Compose your meal',
  hero_title: 'Your fresh ingredients,\nchosen by you',
  hero_sub: 'Choose each ingredient, adjust quantities, and compose the dish that suits you.',
  hero_cta_compose: 'Compose my meal',
  hero_cta_browse: 'Browse catalogue',
  how_title: 'How it works?',
  how_step1: 'Choose your ingredients',
  how_step1_desc: 'Browse the catalogue and add the ingredients you want.',
  how_step2: 'Pay securely',
  how_step2_desc: 'Bank card, Mobile Money, PayPal, or cash on delivery.',
  how_step3: 'Your rider shops at the market',
  how_step3_desc: 'Our riders buy your fresh ingredients and deliver them.',
  popular_title: 'Popular',
  new_title: 'New',
  see_all: 'See all',

  // ─── Catalogue
  catalogue_compose: 'Compose your meal',
  catalogue_search: 'Search a product...',
  catalogue_filter: 'Filter',
  catalogue_sort: 'Sort',
  catalogue_no_result: 'No product found',
  catalogue_add_to_cart: 'Add to cart',
  catalogue_customize: 'Customize',
  catalogue_view: 'View details',
  product_ingredients: 'Ingredients',
  product_quantity: 'Quantity',
  product_unit_price: 'Unit price',
  product_total: 'Total',
  product_back: 'Back',
  product_buy: 'Buy now',

  // ─── Cart / Checkout
  cart_title: 'My cart',
  cart_empty: 'Your cart is empty',
  cart_empty_cta: 'Browse catalogue',
  cart_total: 'Total',
  cart_subtotal: 'Subtotal',
  cart_delivery: 'Delivery fee',
  cart_free_delivery: 'Free delivery',
  cart_checkout: 'Checkout',
  cart_continue_shopping: 'Continue shopping',
  cart_remove: 'Remove',
  checkout_title: 'Complete your order',
  checkout_step_address: 'Address',
  checkout_step_slot: 'Delivery',
  checkout_step_payment: 'Payment',
  checkout_address: 'Delivery address',
  checkout_address_add: 'Add an address',
  checkout_address_select: 'Select an address',
  checkout_address_label: 'Label',
  checkout_address_quartier: 'District',
  checkout_address_ville: 'City',
  checkout_address_rue: 'Street (optional)',
  checkout_address_save: 'Save',
  checkout_address_cancel: 'Cancel',
  checkout_slot: 'Delivery slot',
  checkout_slot_morning: 'Morning',
  checkout_slot_noon: 'Noon',
  checkout_slot_evening: 'Evening',
  checkout_weight: 'Estimated order weight (optional)',
  checkout_weight_hint: 'A weight estimate helps calculate the exact delivery fee.',
  checkout_payment: 'Payment method',
  checkout_next: 'Next',
  checkout_confirm: 'Confirm & Pay',
  checkout_back: 'Back',
  payment_mtn: 'MTN Mobile Money',
  payment_orange: 'Orange Money',
  payment_stripe: 'Credit card (Visa/Mastercard)',
  payment_paypal: 'PayPal',
  payment_cash: 'Cash on delivery',
  payment_pay_on_delivery: 'Pay at delivery',
  payment_instant: 'Instant payment',
  payment_phone_label: 'Mobile Money number',
  payment_phone_placeholder: '6XX XXX XXX',
  payment_stripe_info: 'You will be redirected to the secure Stripe page to enter your card details (Visa, Mastercard).',
  payment_paypal_info: 'You will be redirected to PayPal to complete the payment with your PayPal account or international card.',
  payment_momo_info: 'You will receive a USSD prompt on your phone to confirm payment with your PIN code.',
  payment_secure: '100% secure payment · Encrypted data',
  verifying_payment: 'Verifying payment…',
  please_wait: 'Please wait while we confirm your transaction.',
  payment_confirmed: 'Payment confirmed!',
  order_success_msg: 'Your order has been registered. You will be notified once it is ready.',
  payment_failed: 'Payment not confirmed',
  payment_failed_msg: 'The transaction could not be validated.',
  back_to_cart: 'Back to cart',
  order_confirmed: 'Order confirmed!',
  invoice: 'Invoice',
  view_orders: 'View my orders',
  back_home: 'Back to home',

  // ─── Login / Signup
  login_title: 'Welcome back!',
  login_sub: 'Sign in to access your account',
  login_phone: 'Phone',
  login_password: 'Password',
  login_forgot: 'Forgot password?',
  login_submit: 'Sign in',
  login_no_account: 'No account yet?',
  login_create: 'Create an account',
  signup_title: 'Create an account',
  signup_sub: 'Join ComeBuy in a few seconds',
  signup_name: 'Full name',
  signup_email: 'Email (optional)',
  signup_phone: 'Phone',
  signup_password: 'Password',
  signup_role: 'I am a',
  signup_role_client: 'Customer',
  signup_role_delivery: 'Rider',
  signup_submit: 'Sign up',
  signup_have_account: 'Already have an account?',
  signup_login: 'Sign in',
  otp_title: 'Verification',
  otp_sub: 'Enter the OTP code received by SMS',
  otp_resend: 'Resend code',
  otp_verify: 'Verify',

  // ─── Profile
  profile_title: 'My profile',
  profile_personal: 'Personal information',
  profile_name: 'Full name',
  profile_email: 'Email',
  profile_phone: 'Phone',
  profile_role: 'Role',
  profile_member_since: 'Member since',
  profile_save: 'Save',
  profile_change_password: 'Change password',
  profile_old_password: 'Old password',
  profile_new_password: 'New password',
  profile_confirm_password: 'Confirm new password',
  orders_title: 'My orders',
  orders_empty: 'You have no orders yet',
  orders_status_pending: 'Pending payment',
  orders_status_paid: 'Paid',
  orders_status_preparing: 'Preparing',
  orders_status_delivering: 'Out for delivery',
  orders_status_delivered: 'Delivered',
  orders_status_cancelled: 'Cancelled',
  orders_track: 'Track',
  orders_details: 'Details',
  addresses_title: 'My addresses',
  addresses_empty: 'No saved address',
  addresses_add: 'Add an address',
  addresses_default: 'Default address',
  addresses_edit: 'Edit',
  addresses_delete: 'Delete',
  loyalty_title: 'Loyalty Program',
  loyalty_points: 'Points',
  loyalty_level: 'Level',
  notif_title: 'Notifications',
  notif_empty: 'No notifications',
  notif_mark_read: 'Mark all as read',
  help_title: 'Help & Support',
  help_contact: 'Contact us',

  // ─── Footer
  footer_about: 'About',
  footer_help: 'Help',
  footer_terms: 'Terms & Conditions',
  footer_privacy: 'Privacy policy',
  footer_rights: 'All rights reserved.',
  footer_follow: 'Follow us',

  // ─── Common
  loading: 'Loading…',
  error_generic: 'An error occurred',
  retry: 'Retry',
  cancel: 'Cancel',
  confirm: 'Confirm',
  save: 'Save',
  delete: 'Delete',
  edit: 'Edit',
  close: 'Close',
  yes: 'Yes',
  no: 'No',
  search_placeholder: 'Search…',
  required: 'Required',
  optional: 'Optional',
  total: 'Total',
  qty: 'Qty',
  lang_label: 'EN',
  lang_switch_tooltip: 'Passer en Français',
}

const dictionaries = { fr, en }

export const useLang = create(persist((set, get) => ({
  lang: 'fr',
  toggle: () => set({ lang: get().lang === 'fr' ? 'en' : 'fr' }),
  setLang: (l) => set({ lang: l }),
}), { name: 'lang' }))

// Hook réactif : se ré-exécute quand `lang` change → re-render des composants qui l'utilisent
export const useT = () => {
  const lang = useLang(s => s.lang)
  return (key) => dictionaries[lang]?.[key] ?? dictionaries.fr[key] ?? key
}

export default useLang

